### PR TITLE
UdpClient sample pack

### PR DESCRIPTION
**Pull request by oblaise**
Sample pack for UdpClient

## Description
Three different samples that show how to use UdpClient in different situations.

## Motivation and Context
Show how to use UdpClient.

## How Has This Been Tested?
On an ESP32 device

## Types of changes
- [ ] Improvement (non-breaking change that improves a sample)
- [ ] Bug fix (fixes an issue with a current sample)
- [x] New Sample (adds a new sample)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: oblaise <16148676+oblaise@users.noreply.github.com>

### CODE REVIEW

**Review by josesimoes — COMMENTED** [review]
This is good stuff!!! 

If would be great if the readme had a section explaining the differences on using WiFi device or not. Like the need to add a ref to `System.Device.WiFi` and uncoment the define at the top of the program source file.

As it is now, the projects are referencing WiFi, but the define is commented, which will cause issues when deploying to a a target that doesn't have WiFi support .

**Comment by oblaise** [comment]
So if I understand well I should remove the wifi reference in the project and put a comment in read me on how to add WiFi ?

**Comment by oblaise** [comment]
I can also manage that on the project level :

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
...
  <PropertyGroup>
...
    <AssemblyName>UdpEchoServer</AssemblyName>
    <TargetFrameworkVersion>v1.0</TargetFrameworkVersion>
    <!-- Uncomment the following line if you want to enable WIFI in the sample -->
    <!-- <DefineConstants>$(DefineConstants);HAS_WIFI;</DefineConstants> -->
  </PropertyGroup>
...
  <ItemGroup>
...
    <Reference Include="System.Device.WiFi" Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*HAS_WIFI(;.*)*$'))">
      <HintPath>..\packages\nanoFramework.System.Device.WiFi.1.4.0-preview.34\lib\System.Device.WiFi.dll</HintPath>
    </Reference>
...
  </ItemGroup>
...
</Project>
```

**Comment by josesimoes** [comment]
> So if I understand well I should remove the wifi reference in the project and put a comment in read me on how to add WiFi ?

That's the best way to deal with these differences, considering what's available.

**Review by josesimoes — APPROVED** [review]
LGTM! Thanks for the extra mile adding these samples. 👍🏻 💯

**Pull request merged**
