### PR TITLE
Update comment on ESP32 GPIO pin choice

### PR DESCRIPTION
**Pull request by info-lvsys**

### CODE REVIEW

**Comment by josesimoes** [comment]
Hi @info-lvsys !

Thank you for your contribution improving nanoFramework samples.

Question: what DevKit are you refering to? On the ESP32-WROVER-KIT I have, changing the GPIO from 4 to 2 makes the green LED blink instead of the blue one (both on the tri-colour LED).

**Comment by info-lvsys** [comment]
Oh interesting. I have the Xiuxin ESP32 Development Board, with the ESP Wroom 32 chip. On that board, using PIN 2 blinks nothing.

**Comment by josesimoes** [comment]
From the look of it, it's a regular ESP32-WROOM, there are no LEDs connected to any GPIO... so it doesn't matter if you have there 2 or 4 (as it was)… Care to confirm at your end?

**Comment by info-lvsys** [comment]
Hi

I confirm on Xiuxin ESP32 Development Board, GPIO 2 is connected to the blue on board LED.

See the pin out documented here:  https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

Maybe just reject my commit - all that is needed is to tell people in the comment that depending on the dev board if 4 does not work, that the should try pin 2 as well.

**Comment by josesimoes** [comment]
That seems a more reasonable approach.
Care to update the comment instead and maybe explain that depending on the ESP32 variant the gpio maybe be different from baird to board?

**Comment by info-lvsys** [comment]
OK, just did.

**Comment by josesimoes** [comment]
@info-lvsys are you on our Discord community? 
What name should I use for listing you at the contributors hall?

**Comment by info-lvsys** [comment]
Hi - Wasn't on Discord. Just joined it. you can use LVSYS for the contributors hall if you want - I feel I made too small a contrib ;) must say.

**Comment by josesimoes** [comment]
Will do. This project lives from all contributions: large and  small. If more people were willing to contribute, even with small ones, we would way ahead! 😉

**Pull request merged**
