### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by laurentksh**
## Description
Fixed various broken links due to branch rename.

## Motivation and Context
As some links were broken due to the renaming of the default branch I have taken the initiative to fix them and submit a PR.

## How Has This Been Tested?
Clicked on the new links and they work.

## Types of changes

- [ ] Improvement (non-breaking change that improves a sample)
- [ ] Bug fix (fixes an issue with a current sample)
- [ ] New Sample (adds a new sample)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Documentation update

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: @LaurentKsh

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=160) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=160) before we can accept your contribution.<br/><br/>:x: laurentksh [sign now](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=160)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/Samples?pullRequest=160) it.</sub>

**Review by josesimoes — APPROVED** [review]
Nice catch! Thank you for fixing these! 👏🏻

**Comment by josesimoes** [comment]
Ignoring the build errors, will be fixed later.

**Comment by laurentksh** [comment]
@josesimoes Thank you for the quick review and approval, happy to contribute to this neat project !
Should I ignore @nfbot message or add my name to the contributors list as suggested ?

**Comment by josesimoes** [comment]
> @josesimoes Thank you for the quick review and approval, happy to contribute to this neat project !

Cool! Thank YOU for contributing. 😄 (and keep those PRs coming!) 

> Should I ignore @nfbot message or add my name to the contributors list as suggested ?

Please go ahead and submit a PR with it. If you don't do it yourself, I'll eventually end up doing it as I feel that everyone contributing deserves to be mentioned. 😜

**Pull request merged**
