### PR TITLE
Add DigiCert Global Root G2 root CA certificate

### PR DESCRIPTION
**Pull request by matsujirushi**
## Motivation and Context

- Closes nanoFramework/Home#1325

## How Has This Been Tested?

I tested to connect both Azure IoT Hub. (baltimore root cert. and digicert root cert.)

## Types of changes

- [x] Improvement (non-breaking change that improves a sample)
- [ ] Bug fix (fixes an issue with a current sample)
- [ ] New Sample (adds a new sample)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
@matsujirushi the build is currently failing because of other issues in the MQTT samples that are outdated. 
It needs to be fixed on a separate PR before moving forward with this one.

**Comment by matsujirushi** [comment]
Hi @josesimoes ,
I see.
Can I include to fix MQTT problem in this PR?

**Comment by josesimoes** [comment]
@matsujirushi please make that a separate PR. This one it's about the root certs, totally unrelated. 😉

**Review by josesimoes — COMMENTED** [review]
The new resources don't seem to be using the correct generator...
Please make sure to use the existing `Resources.resx` file to make it easy.

**Comment by matsujirushi** [comment]
@josesimoes ,

> The new resources don't seem to be using the correct generator...

Could you give me more details?

**Comment by matsujirushi** [comment]
Hi @josesimoes ,

1. Change certificate format from .der to .pem
  To accommodate Baltimore CyberTrust CA and DigiCert Global G2 CA at the same time.
  Change resource type to String so that .pem works with X509Certificate class.
2. Rename Resources.resx to Resource.resx
  The name was different depending on the project, so I made it the same.

Using ESP32, I tested the connection to Azure IoT Hub and Azure IoT Hub DPS of each server certificate and it was fine.

Please let me know if there are any problems so I can look into it. (e.g. compile error, runtime error, ...)

**Comment by Ellerbach** [comment]
So question is: with pem, you can have both certs at the same time and the bellow platform is choosing between those. Correct?

**Comment by Ellerbach** [comment]
So question is: with pem, you can have both certs at the same time and the bellow platform is choosing between those. Correct?

**Comment by matsujirushi** [comment]
@Ellerbach ,
Yes. 😎

**Review by Ellerbach — APPROVED** [review]
All checked and seems to work properly. Updated to the latest version. Thanks again for updating all this!

**Pull request merged**
