### PR TITLE
Update strip the device name from SAS token

### PR DESCRIPTION
**Pull request by ikivanc**
## Description
In code implementation, device name extraction was looking for an additional character which is not part of SAS Token anymore.
Removed that character and updated strip line

## Motivation and Context
This small change helps to strip device name correctly

## How Has This Been Tested?
Build and deployed the code to ESP32 device

## Types of changes
Change the strip line works with SAS token

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=147) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=147) before we can accept your contribution.<br/><br/>:x: ikivanc [sign now](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=147)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/Samples?pullRequest=147) it.</sub>

**Review by Ellerbach — COMMENTED** [review]
Are you sure this is not creating side effect? There is maybe a good reason why it was "1&" and not just "&"?

**Comment by ikivanc** [comment]
`SharedAccessSignature sr=<iotHubName>.azure-devices.net%2Fdevices%2F<deviceName>&sig=<signature>`

SAS structure doesn't have additional "1" character before "&" and sample is not extracting correct device name as it is, with this small change it's is working as expected.

**Review by Ellerbach — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
